version: '3.8'
services:
  gymetr-login:
    build: ./backend/GYMETR-login
    ports:
      - "8080:8080"
    container_name: gymetr-login
  gymetr-membership:
    build: ./backend/GYMETR-Membership
    ports:
      - "8081:8081"
    container_name: gymetr-membership
  gymetra-frontend:
    build: ./frontend/gymetra-frontend
    ports:
      - "8100:80"
    container_name: gymetra-frontend
