version: '3.9'

services:
  backend:
    build: 
      context: ./backend/GYMETR-login
      dockerfile: Dockerfile
    container_name: gymetra_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xmx512m -Xms256m
    restart: unless-stopped
    networks:
      - gymetra-net

  frontend:
    build: 
      context: ./frontend/gymetra-frontend
      dockerfile: Dockerfile
    container_name: gymetra_frontend
    ports:
      - "8100:80"   # Frontend accesible en http://localhost:8100
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - gymetra-net
    environment:
      - NODE_ENV=production

networks:
  gymetra-net:
    driver: bridge
